### ISSUE TITLE
How do you add Door Sensors and Security Devices?

### ISSUE THREAD

**Issue by sebastienvg** [enishoca/pimatic-mochad-simple#1]
That must be trivial but I can't figure how to handle those doors/windows sensors DS12A or any security devices. However, I was able to use the HR12A remote as well as MS16A motion sensor.
Can you shade some light on how to do this?

**Comment by enishoca** [comment]
Sorry I missed this - 
I haven't used pimatic in a while and don't have it setup to test.  So this from memory and looking at code.  Each security device has a hex code and emits a function -  The device code is returned in the housecode field and the function is returned in the state field.  Its not a simple on/off so you will need to look at the X10Message that is emitted and use that to create pimatic rules.  Don't remember how that is done now.
